### Numpy

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays. It is the fundamental package for scientific computing with Python. Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data

### Arrays in Numpy 

A NumPy array (ndarray) is a collection of elements of the same data type stored in a multidimensional structure. Arrays provide an efficient way to store and perform operations on numerical data.

- Number of dimensions in an array is called its rank.
- Size of the array along each dimension is called its shape.
- Elements are accessed using square brackets [] and arrays are commonly created from Python lists.


In [27]:
import numpy as n 

a = n.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0] , a[1])

# two dimensional array 

b = n.array([[1,2,3],[4,5,6]])
print(type(b))
print(b.shape)
print(b[0,0 ],b[0,1] , b[1,2])

<class 'numpy.ndarray'>
(3,)
1 2
<class 'numpy.ndarray'>
(2, 3)
1 2 6


Numpy also provides many functions to create arrays


In [47]:
import numpy as n 

a = n.zeros((2,2))
print(a)
print ("--------")
b = n.ones((1,2))
print(b)
c = n.full((3,3) , 23)
print("---------")
print(c)
print ("--------")
d = n.eye(7) #creates an identity matrix of size 7x7
print(d)
print ("--------")
e = n.random.random((3,3,3))
print(e)

[[0. 0.]
 [0. 0.]]
--------
[[1. 1.]]
---------
[[23 23 23]
 [23 23 23]
 [23 23 23]]
--------
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
--------
[[[0.85981534 0.07869991 0.41756263]
  [0.01274255 0.96153179 0.36183916]
  [0.27643303 0.31362924 0.38901779]]

 [[0.8611349  0.21445725 0.64381007]
  [0.37100865 0.12812568 0.45410412]
  [0.28461998 0.09154276 0.71072378]]

 [[0.69785487 0.31992372 0.47858987]
  [0.0428239  0.21172374 0.81835815]
  [0.28709    0.77193038 0.94757749]]]


## Array Indexing 
numpy offers several ways to index into arrays


In [49]:
import numpy as n 

a = n.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a[:2 , 1:3]
print(b)

[[2 3]
 [6 7]]


# Datatypes 

Every numpy array is a grid of elemets of the same type ( integer , float ) 

In [57]:
import numpy as n 

x = n.array([1,2])
print(x.dtype)

x = n.array([1.2, 3,4])
print(x.dtype)

x = n.array([1, 2], dtype=n.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"


int64
float64
int64


# Array Math 
basic mathematical function operate elementwise on arrays and are available both as a operator overloads and as functions in numpy 

In [65]:
import numpy as n 
x = n.array([[1,2] , [3,4]] ,dtype=n.float64)
y = n.array([[5,6],[7,8]] , dtype=n.float64)

# element_wise sum; both produce the array 

print(x+y)
print(n.add(x,y))

def line(i):
    for _ in range(i):
        print("-------")


line(1)

print(n.subtract(x,y))

line(1)

print(n.multiply(x,y))

line(1)
print(n.divide(x,y))

line(1)
print(n.sqrt(x))



[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
-------
[[-4. -4.]
 [-4. -4.]]
-------
[[ 5. 12.]
 [21. 32.]]
-------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
-------
[[1.         1.41421356]
 [1.73205081 2.        ]]


# Broadcasting 
Broadcasting is a powerful mechanism that allows numpy to work with arrays of differnent shapes when performing arithmetic operations . 
Frequently we have a smaller array and a larger array , we want to use the smaller array multiple times to perform some operation on the larger array . 

In [70]:
import numpy as n 

x = n.array([[1,2,3],[4,5,6],[7,8,9]])
v = n.array([1,0,1])
y = n.empty_like(x)   # Create an empty matrix with the same shape as x

print(y)

def line(i):
    for _ in range(i):
        print('---------')

line(1)



# add the vector v to each row of the matrix x with an explicit loop 

for i in range(3):
    y[i,:] = x[i,:] + v

print(y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
